/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImageToPdfRouteImport } from './routes/image-to-pdf'
import { Route as LockPdfRouteImport } from './routes/lock-pdf'
import { Route as MergePdfRouteImport } from './routes/merge-pdf'
import { Route as SignPdfRouteImport } from './routes/sign-pdf'
import { Route as UnlockPdfRouteImport } from './routes/unlock-pdf'
import { Route as WatermarkPdfRouteImport } from './routes/watermark-pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToPdfRoute = ImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const LockPdfRoute = LockPdfRouteImport.update({
  id: '/lock-pdf',
  path: '/lock-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const MergePdfRoute = MergePdfRouteImport.update({
  id: '/merge-pdf',
  path: '/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const SignPdfRoute = SignPdfRouteImport.update({
  id: '/sign-pdf',
  path: '/sign-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockPdfRoute = UnlockPdfRouteImport.update({
  id: '/unlock-pdf',
  path: '/unlock-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const WatermarkPdfRoute = WatermarkPdfRouteImport.update({
  id: '/watermark-pdf',
  path: '/watermark-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/lock-pdf': typeof LockPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/sign-pdf': typeof SignPdfRoute
  '/unlock-pdf': typeof UnlockPdfRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/lock-pdf': typeof LockPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/sign-pdf': typeof SignPdfRoute
  '/unlock-pdf': typeof UnlockPdfRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/lock-pdf': typeof LockPdfRoute
  '/merge-pdf': typeof MergePdfRoute
  '/sign-pdf': typeof SignPdfRoute
  '/unlock-pdf': typeof UnlockPdfRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/image-to-pdf'
    | '/lock-pdf'
    | '/merge-pdf'
    | '/sign-pdf'
    | '/unlock-pdf'
    | '/watermark-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/image-to-pdf'
    | '/lock-pdf'
    | '/merge-pdf'
    | '/sign-pdf'
    | '/unlock-pdf'
    | '/watermark-pdf'
  id:
    | '__root__'
    | '/'
    | '/image-to-pdf'
    | '/lock-pdf'
    | '/merge-pdf'
    | '/sign-pdf'
    | '/unlock-pdf'
    | '/watermark-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageToPdfRoute: typeof ImageToPdfRoute
  LockPdfRoute: typeof LockPdfRoute
  MergePdfRoute: typeof MergePdfRoute
  SignPdfRoute: typeof SignPdfRoute
  UnlockPdfRoute: typeof UnlockPdfRoute
  WatermarkPdfRoute: typeof WatermarkPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-pdf': {
      id: '/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/image-to-pdf'
      preLoaderRoute: typeof ImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock-pdf': {
      id: '/lock-pdf'
      path: '/lock-pdf'
      fullPath: '/lock-pdf'
      preLoaderRoute: typeof LockPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-pdf': {
      id: '/merge-pdf'
      path: '/merge-pdf'
      fullPath: '/merge-pdf'
      preLoaderRoute: typeof MergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-pdf': {
      id: '/sign-pdf'
      path: '/sign-pdf'
      fullPath: '/sign-pdf'
      preLoaderRoute: typeof SignPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock-pdf': {
      id: '/unlock-pdf'
      path: '/unlock-pdf'
      fullPath: '/unlock-pdf'
      preLoaderRoute: typeof UnlockPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watermark-pdf': {
      id: '/watermark-pdf'
      path: '/watermark-pdf'
      fullPath: '/watermark-pdf'
      preLoaderRoute: typeof WatermarkPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageToPdfRoute: ImageToPdfRoute,
  LockPdfRoute: LockPdfRoute,
  MergePdfRoute: MergePdfRoute,
  SignPdfRoute: SignPdfRoute,
  UnlockPdfRoute: UnlockPdfRoute,
  WatermarkPdfRoute: WatermarkPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
